# docker run -e JAEGER_COLLECTOR_URL=http://192.168.1.124:14268 omnition/synthetic-load-generator:1.0.25
# go run ./cmd/server --config=./cmd/server/config.yaml
receivers:
  jaeger:
    protocols:
      thrift-http:
        endpoint: "0.0.0.0:14268"
exporters:
  native:
    block_duration: 5m
processors:
  stream: {}
extensions:
  health_check: {}
  pprof: {}
  zpages: {}
service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [jaeger]
      exporters: [native]
      processors: [stream]
