version: '3.3'
services:
  tsp:
    image: tsp:latest
    command: ["--config","/etc/config/config.yaml"]
    ports:
      - "31234:31234"
      - "31235:31235"
    volumes:
    - ./:/etc/config
  hotrod:
    image: jaegertracing/example-hotrod:latest
    ports: 
      - "8080:8080"
    command: ["all"]
    environment:
      - JAEGER_ENDPOINT=http://tsp:14268/api/traces
    depends_on:
      - tsp
  synthetic-load-generator:
    image: omnition/synthetic-load-generator:1.0.25
    volumes:
      - ./load-generator.json:/etc/load-generator.json
    environment:
      - TOPOLOGY_FILE=/etc/load-generator.json
      - JAEGER_COLLECTOR_URL=http://tsp:14268
