// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blerg.proto

/*
Package blergpb is a generated protocol buffer package.

It is generated from these files:
	blerg.proto

It has these top-level messages:
	StreamRequest
	TraceRequest
	SpanRequest
	SpanResponse
	Span
	ParentSpan
*/
package blergpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StreamRequest struct {
	RequestedBatchSize int32 `protobuf:"varint,1,opt,name=requestedBatchSize" json:"requestedBatchSize,omitempty"`
	RequestedRate      int32 `protobuf:"varint,2,opt,name=requestedRate" json:"requestedRate,omitempty"`
}

func (m *StreamRequest) Reset()                    { *m = StreamRequest{} }
func (m *StreamRequest) String() string            { return proto.CompactTextString(m) }
func (*StreamRequest) ProtoMessage()               {}
func (*StreamRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StreamRequest) GetRequestedBatchSize() int32 {
	if m != nil {
		return m.RequestedBatchSize
	}
	return 0
}

func (m *StreamRequest) GetRequestedRate() int32 {
	if m != nil {
		return m.RequestedRate
	}
	return 0
}

type TraceRequest struct {
	Params      *StreamRequest `protobuf:"bytes,1,opt,name=params" json:"params,omitempty"`
	ProcessName string         `protobuf:"bytes,2,opt,name=ProcessName,json=processName" json:"ProcessName,omitempty"`
}

func (m *TraceRequest) Reset()                    { *m = TraceRequest{} }
func (m *TraceRequest) String() string            { return proto.CompactTextString(m) }
func (*TraceRequest) ProtoMessage()               {}
func (*TraceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TraceRequest) GetParams() *StreamRequest {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *TraceRequest) GetProcessName() string {
	if m != nil {
		return m.ProcessName
	}
	return ""
}

type SpanRequest struct {
	Params        *StreamRequest `protobuf:"bytes,1,opt,name=params" json:"params,omitempty"`
	OperationName string         `protobuf:"bytes,2,opt,name=OperationName,json=operationName" json:"OperationName,omitempty"`
	ProcessName   string         `protobuf:"bytes,3,opt,name=ProcessName,json=processName" json:"ProcessName,omitempty"`
}

func (m *SpanRequest) Reset()                    { *m = SpanRequest{} }
func (m *SpanRequest) String() string            { return proto.CompactTextString(m) }
func (*SpanRequest) ProtoMessage()               {}
func (*SpanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SpanRequest) GetParams() *StreamRequest {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *SpanRequest) GetOperationName() string {
	if m != nil {
		return m.OperationName
	}
	return ""
}

func (m *SpanRequest) GetProcessName() string {
	if m != nil {
		return m.ProcessName
	}
	return ""
}

type SpanResponse struct {
	Dropped int32   `protobuf:"varint,1,opt,name=dropped" json:"dropped,omitempty"`
	Spans   []*Span `protobuf:"bytes,2,rep,name=spans" json:"spans,omitempty"`
}

func (m *SpanResponse) Reset()                    { *m = SpanResponse{} }
func (m *SpanResponse) String() string            { return proto.CompactTextString(m) }
func (*SpanResponse) ProtoMessage()               {}
func (*SpanResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SpanResponse) GetDropped() int32 {
	if m != nil {
		return m.Dropped
	}
	return 0
}

func (m *SpanResponse) GetSpans() []*Span {
	if m != nil {
		return m.Spans
	}
	return nil
}

type Span struct {
	TraceID       []byte      `protobuf:"bytes,1,opt,name=traceID,proto3" json:"traceID,omitempty"`
	SpanID        []byte      `protobuf:"bytes,2,opt,name=spanID,proto3" json:"spanID,omitempty"`
	ParentSpanID  []byte      `protobuf:"bytes,3,opt,name=parentSpanID,proto3" json:"parentSpanID,omitempty"`
	ProcessName   string      `protobuf:"bytes,4,opt,name=processName" json:"processName,omitempty"`
	OperationName string      `protobuf:"bytes,5,opt,name=operationName" json:"operationName,omitempty"`
	StartTime     int64       `protobuf:"varint,6,opt,name=startTime" json:"startTime,omitempty"`
	Duration      int64       `protobuf:"varint,7,opt,name=duration" json:"duration,omitempty"`
	Parent        *ParentSpan `protobuf:"bytes,8,opt,name=parent" json:"parent,omitempty"`
}

func (m *Span) Reset()                    { *m = Span{} }
func (m *Span) String() string            { return proto.CompactTextString(m) }
func (*Span) ProtoMessage()               {}
func (*Span) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Span) GetTraceID() []byte {
	if m != nil {
		return m.TraceID
	}
	return nil
}

func (m *Span) GetSpanID() []byte {
	if m != nil {
		return m.SpanID
	}
	return nil
}

func (m *Span) GetParentSpanID() []byte {
	if m != nil {
		return m.ParentSpanID
	}
	return nil
}

func (m *Span) GetProcessName() string {
	if m != nil {
		return m.ProcessName
	}
	return ""
}

func (m *Span) GetOperationName() string {
	if m != nil {
		return m.OperationName
	}
	return ""
}

func (m *Span) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Span) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Span) GetParent() *ParentSpan {
	if m != nil {
		return m.Parent
	}
	return nil
}

type ParentSpan struct {
	ProcessName   string `protobuf:"bytes,1,opt,name=processName" json:"processName,omitempty"`
	OperationName string `protobuf:"bytes,2,opt,name=operationName" json:"operationName,omitempty"`
	StartTime     int64  `protobuf:"varint,3,opt,name=startTime" json:"startTime,omitempty"`
	Duration      int64  `protobuf:"varint,4,opt,name=duration" json:"duration,omitempty"`
}

func (m *ParentSpan) Reset()                    { *m = ParentSpan{} }
func (m *ParentSpan) String() string            { return proto.CompactTextString(m) }
func (*ParentSpan) ProtoMessage()               {}
func (*ParentSpan) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ParentSpan) GetProcessName() string {
	if m != nil {
		return m.ProcessName
	}
	return ""
}

func (m *ParentSpan) GetOperationName() string {
	if m != nil {
		return m.OperationName
	}
	return ""
}

func (m *ParentSpan) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *ParentSpan) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func init() {
	proto.RegisterType((*StreamRequest)(nil), "blergpb.StreamRequest")
	proto.RegisterType((*TraceRequest)(nil), "blergpb.TraceRequest")
	proto.RegisterType((*SpanRequest)(nil), "blergpb.SpanRequest")
	proto.RegisterType((*SpanResponse)(nil), "blergpb.SpanResponse")
	proto.RegisterType((*Span)(nil), "blergpb.Span")
	proto.RegisterType((*ParentSpan)(nil), "blergpb.ParentSpan")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SpanStream service

type SpanStreamClient interface {
	QuerySpans(ctx context.Context, in *SpanRequest, opts ...grpc.CallOption) (SpanStream_QuerySpansClient, error)
	QueryTraces(ctx context.Context, in *TraceRequest, opts ...grpc.CallOption) (SpanStream_QueryTracesClient, error)
}

type spanStreamClient struct {
	cc *grpc.ClientConn
}

func NewSpanStreamClient(cc *grpc.ClientConn) SpanStreamClient {
	return &spanStreamClient{cc}
}

func (c *spanStreamClient) QuerySpans(ctx context.Context, in *SpanRequest, opts ...grpc.CallOption) (SpanStream_QuerySpansClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_SpanStream_serviceDesc.Streams[0], c.cc, "/blergpb.SpanStream/QuerySpans", opts...)
	if err != nil {
		return nil, err
	}
	x := &spanStreamQuerySpansClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SpanStream_QuerySpansClient interface {
	Recv() (*SpanResponse, error)
	grpc.ClientStream
}

type spanStreamQuerySpansClient struct {
	grpc.ClientStream
}

func (x *spanStreamQuerySpansClient) Recv() (*SpanResponse, error) {
	m := new(SpanResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *spanStreamClient) QueryTraces(ctx context.Context, in *TraceRequest, opts ...grpc.CallOption) (SpanStream_QueryTracesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_SpanStream_serviceDesc.Streams[1], c.cc, "/blergpb.SpanStream/QueryTraces", opts...)
	if err != nil {
		return nil, err
	}
	x := &spanStreamQueryTracesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SpanStream_QueryTracesClient interface {
	Recv() (*SpanResponse, error)
	grpc.ClientStream
}

type spanStreamQueryTracesClient struct {
	grpc.ClientStream
}

func (x *spanStreamQueryTracesClient) Recv() (*SpanResponse, error) {
	m := new(SpanResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for SpanStream service

type SpanStreamServer interface {
	QuerySpans(*SpanRequest, SpanStream_QuerySpansServer) error
	QueryTraces(*TraceRequest, SpanStream_QueryTracesServer) error
}

func RegisterSpanStreamServer(s *grpc.Server, srv SpanStreamServer) {
	s.RegisterService(&_SpanStream_serviceDesc, srv)
}

func _SpanStream_QuerySpans_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SpanRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SpanStreamServer).QuerySpans(m, &spanStreamQuerySpansServer{stream})
}

type SpanStream_QuerySpansServer interface {
	Send(*SpanResponse) error
	grpc.ServerStream
}

type spanStreamQuerySpansServer struct {
	grpc.ServerStream
}

func (x *spanStreamQuerySpansServer) Send(m *SpanResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SpanStream_QueryTraces_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TraceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SpanStreamServer).QueryTraces(m, &spanStreamQueryTracesServer{stream})
}

type SpanStream_QueryTracesServer interface {
	Send(*SpanResponse) error
	grpc.ServerStream
}

type spanStreamQueryTracesServer struct {
	grpc.ServerStream
}

func (x *spanStreamQueryTracesServer) Send(m *SpanResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _SpanStream_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blergpb.SpanStream",
	HandlerType: (*SpanStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QuerySpans",
			Handler:       _SpanStream_QuerySpans_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "QueryTraces",
			Handler:       _SpanStream_QueryTraces_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "blerg.proto",
}

func init() { proto.RegisterFile("blerg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0x71, 0xd2, 0xa6, 0xbb, 0x93, 0xe4, 0x62, 0x60, 0x65, 0xad, 0x38, 0x44, 0x61, 0x0f,
	0x95, 0x90, 0x22, 0x54, 0xce, 0x08, 0x09, 0xed, 0x65, 0x0f, 0xc0, 0xe2, 0xec, 0x03, 0xe0, 0x36,
	0x23, 0xa8, 0x44, 0x12, 0x63, 0xbb, 0x07, 0xb8, 0x73, 0x02, 0xf1, 0xcc, 0xc8, 0x76, 0x36, 0x7f,
	0xda, 0xaa, 0xa0, 0xbd, 0x65, 0xbe, 0x99, 0xcc, 0xfc, 0xfc, 0xd9, 0x03, 0xf1, 0xfa, 0x2b, 0xaa,
	0xcf, 0x85, 0x54, 0xad, 0x69, 0xe9, 0xc2, 0x05, 0x72, 0x9d, 0x23, 0xa4, 0xa5, 0x51, 0x28, 0x6a,
	0x8e, 0xdf, 0x76, 0xa8, 0x0d, 0x2d, 0x80, 0x2a, 0xff, 0x89, 0xd5, 0x5b, 0x61, 0x36, 0x5f, 0xca,
	0xed, 0x0f, 0x64, 0x24, 0x23, 0xcb, 0x39, 0x3f, 0x92, 0xa1, 0x57, 0x90, 0xf6, 0x2a, 0x17, 0x06,
	0x59, 0xe0, 0x4a, 0xa7, 0x62, 0xfe, 0x09, 0x92, 0x3b, 0x25, 0x36, 0x38, 0x4c, 0x89, 0xa4, 0x50,
	0xa2, 0xd6, 0xae, 0x73, 0xbc, 0xba, 0x28, 0x3a, 0xa0, 0x62, 0x42, 0xc3, 0xbb, 0x2a, 0x9a, 0x41,
	0x7c, 0xab, 0xda, 0x0d, 0x6a, 0xfd, 0x5e, 0xd4, 0x7e, 0xc6, 0x39, 0x8f, 0xe5, 0x20, 0xe5, 0x3f,
	0x09, 0xc4, 0xa5, 0x14, 0xcd, 0x43, 0x27, 0x5c, 0x41, 0xfa, 0x41, 0xa2, 0x12, 0x66, 0xdb, 0x36,
	0xa3, 0x19, 0x69, 0x3b, 0x16, 0xf7, 0x39, 0xc2, 0x43, 0x8e, 0x77, 0x90, 0x78, 0x0c, 0x2d, 0xdb,
	0x46, 0x23, 0x65, 0xb0, 0xa8, 0x54, 0x2b, 0x25, 0x56, 0x9d, 0x89, 0xf7, 0x21, 0x7d, 0x0e, 0x73,
	0x2d, 0x45, 0xa3, 0x59, 0x90, 0x85, 0xcb, 0x78, 0x95, 0x0e, 0x80, 0xf6, 0x7f, 0x9f, 0xcb, 0x7f,
	0x05, 0x30, 0xb3, 0xb1, 0xed, 0x63, 0xac, 0x83, 0x37, 0xd7, 0xae, 0x4f, 0xc2, 0xef, 0x43, 0x7a,
	0x01, 0x91, 0xad, 0xbd, 0xb9, 0x76, 0xc8, 0x09, 0xef, 0x22, 0x9a, 0x43, 0x22, 0x85, 0xc2, 0xc6,
	0x94, 0x3e, 0x1b, 0xba, 0xec, 0x44, 0xb3, 0xe7, 0x19, 0xc1, 0xb3, 0xd9, 0xc1, 0x79, 0xac, 0x2f,
	0x13, 0x0b, 0xd8, 0xfc, 0x98, 0x2f, 0xcf, 0xe0, 0x5c, 0x1b, 0xa1, 0xcc, 0xdd, 0xb6, 0x46, 0x16,
	0x65, 0x64, 0x19, 0xf2, 0x41, 0xa0, 0x97, 0x70, 0x56, 0xed, 0x7c, 0x35, 0x5b, 0xb8, 0x64, 0x1f,
	0xd3, 0x17, 0xee, 0x9e, 0xb0, 0x31, 0xec, 0xcc, 0xdd, 0xd3, 0xe3, 0xde, 0x86, 0xdb, 0x1e, 0x94,
	0x77, 0x25, 0xf9, 0x1f, 0x02, 0x30, 0xc8, 0xfb, 0xf4, 0xe4, 0x3f, 0xe8, 0x83, 0x7f, 0xd2, 0x87,
	0xa7, 0xe8, 0x67, 0x53, 0xfa, 0xd5, 0x6f, 0x02, 0x60, 0x51, 0xfc, 0x9b, 0xa2, 0xaf, 0x01, 0x3e,
	0xee, 0x50, 0x7d, 0xb7, 0x92, 0xa6, 0x4f, 0xa6, 0x37, 0xea, 0x1f, 0xdc, 0xe5, 0xd3, 0x3d, 0xd5,
	0xbf, 0x93, 0xfc, 0xd1, 0x4b, 0x42, 0xdf, 0x40, 0xec, 0x7e, 0x77, 0xab, 0xa2, 0xe9, 0x50, 0x39,
	0xde, 0x9d, 0x13, 0x0d, 0xd6, 0x91, 0xdb, 0xee, 0x57, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x70,
	0xe3, 0x64, 0x92, 0xec, 0x03, 0x00, 0x00,
}
